name: Run clang-format Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './Hurrican/src'
        exclude: 'none'
        extensions: 'cpp,hpp'
        clangFormatVersion: 16
    - uses: EndBug/add-and-commit@v9
      with:
        add: './Hurrican/src'
        author_name: Clang Robot
        author_email: robot@example.com
        message: 'Committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
